INSERT INTO head_gear (head_id, head_name)
VALUES (1, 'Scholar Cowl'),
       (2, 'Cleric Cowl'),
       (3, 'Mage Cowl'),
       (4, 'Druid Cowl'),
       (5, 'Fiend Cowl'),
       (6, 'Cultist Cowl'),
       (7, 'Royal Cowl'),
       (8, 'Cowl of Purity'),
       (9, 'Mercenary Hood'),
       (10, 'Hunter Hood'),
       (11, 'Assassin Hood'),
       (12, 'Stalker Hood'),
       (13, 'Hellion Hood'),
       (14, 'Specter Hood'),
       (15, 'Royal Hood'),
       (16, 'Hood of Tenacity'),
       (17, 'Soldier Helmet'),
       (18, 'Knight Helmet'),
       (19, 'Guardian Helmet'),
       (20, 'Graveguard Helmet'),
       (21, 'Demon Helmet'),
       (22, 'Judicator Helmet'),
       (23, 'Royal Helmet'),
       (24, 'Helmet of Valor'),
       (25, 'Harvester Cap'),
       (26, 'Skinner Cap'),
       (27, 'Miner Cap'),
       (28, 'Quarrier Cap'),
       (29, 'Lumberjack Cap'),
       (30, 'Fisherman Cap')
;

INSERT INTO chest_gear (chest_id, chest_name)
VALUES (1, 'Scholar Robe'),
       (2, 'Cleric Robe'),
       (3, 'Mage Robe'),
       (4, 'Druid Robe'),
       (5, 'Fiend Robe'),
       (6, 'Cultist Robe'),
       (7, 'Royal Robe'),
       (8, 'Robe of Purity'),
       (9, 'Mercenary Jacket'),
       (10, 'Hunter Jacket'),
       (11, 'Assassin Jacket'),
       (12, 'Stalker Jacket'),
       (13, 'Hellion Jacket'),
       (14, 'Specter Jacket'),
       (15, 'Royal Jacket'),
       (16, 'Jacket of Tenacity'),
       (17, 'Soldier Armor'),
       (18, 'Knight Armor'),
       (19, 'Guardian Armor'),
       (20, 'Graveguard Armor'),
       (21, 'Demon Armor'),
       (22, 'Judicator Armor'),
       (23, 'Royal Armor'),
       (24, 'Armor of Valor'),
       (25, 'Harvester Garb'),
       (26, 'Skinner Garb'),
       (27, 'Miner Garb'),
       (28, 'Quarrier Garb'),
       (29, 'Lumberjack Garb'),
       (30, 'Fisherman Garb')
;

INSERT INTO shoes(shoe_id, shoe_name)
VALUES (1, 'Scholar Sandals'),
       (2, 'Cleric Sandals'),
       (3, 'Mage Sandals'),
       (4, 'Druid Sandals'),
       (5, 'Fiend Sandals'),
       (6, 'Cultist Sandals'),
       (7, 'Royal Sandals'),
       (8, 'Sandals of Purity'),
       (9, 'Mercenary Shoes'),
       (10, 'Hunter Shoes'),
       (11, 'Assassin Shoes'),
       (12, 'Stalker Shoes'),
       (13, 'Hellion Shoes'),
       (14, 'Specter Shoes'),
       (15, 'Royal Shoes'),
       (16, 'Shoes of Tenacity'),
       (17, 'Soldier Boots'),
       (18, 'Knight Boots'),
       (19, 'Guardian Boots'),
       (20, 'Graveguard Boots'),
       (21, 'Demon Boots'),
       (22, 'Judicator Boots'),
       (23, 'Royal Boots'),
       (24, 'Boots of Valor'),
       (25, 'Harvester Workboots'),
       (26, 'Skinner Workboots'),
       (27, 'Miner Workboots'),
       (28, 'Quarrier Workboots'),
       (29, 'Lumberjack Workboots'),
       (30, 'Fisherman Workboots')
;

INSERT INTO main_hand(main_hand_id, main_hand_name)
VALUES (1, 'Bow'),
       (2, 'Warbow'),
       (3, 'Longbow'),
       (4, 'Whispering Bow'),
       (5, 'Wailing Bow'),
       (6, 'Bow of Badon'),
       (7, 'Mistpiercer'),
       (8, 'Crossbow'),
       (9, 'Heavy Crossbow'),
       (10, 'Light Crossbow'),
       (11, 'Weeping Repeater'),
       (12, 'Boltcasters'),
       (13, 'Siegebow'),
       (14, 'Energy Shaper'),
       (15, 'Cursed Staff'),
       (16, 'Great Cursed Staff'),
       (17, 'Demonic Staff'),
       (18, 'Lifecurse Staff'),
       (19, 'Cursed Skull'),
       (20, 'Damnation Staff'),
       (21, 'Shadowcaller'),
       (22, 'Fire Staff'),
       (23, 'Great Fire Staff'),
       (24, 'Infernal Staff'),
       (25, 'Wildfire Staff'),
       (26, 'Brimstone Staff'),
       (27, 'Blazing Staff'),
       (28, 'Dawnsong'),
       (29, 'Frost Staff'),
       (30, 'Great Frost Staff'),
       (31, 'Glacial Staff'),
       (32, 'Hoarfrost Staff'),
       (33, 'Icicle Staff'),
       (34, 'Permafrost Prism'),
       (35, 'Chillhowl'),
       (36, 'Arcane Staff'),
       (37, 'Great Arcane Staff'),
       (38, 'Enigmatic Staff'),
       (39, 'Witchwork Staff'),
       (40, 'Occult Staff'),
       (41, 'Malevolent Locus'),
       (42, 'Evensong'),
       (43, 'Holy Staff'),
       (44, 'Great Holy Staff'),
       (45, 'Divine Staff'),
       (46, 'Lifetouch Staff'),
       (47, 'Fallen Staff'),
       (48, 'Redemption Staff'),
       (49, 'Hallowfall'),
       (50, 'Nature Staff'),
       (51, 'Great Nature Staff'),
       (52, 'Wild Staff'),
       (53, 'Druidic Staff'),
       (54, 'Blight Staff'),
       (55, 'Rampant Staff'),
       (56, 'Ironroot Staff'),
       (57, 'Dagger Pair'),
       (58, 'Claws'),
       (59, 'Bloodletter'),
       (60, 'Demonfang'),
       (61, 'Black Hands'),
       (62, 'Deathgivers'),
       (63, 'Bridled Fury'),
       (64, 'Spear'),
       (65, 'Pike'),
       (66, 'Glaive'),
       (67, 'Heron Spear'),
       (68, 'Spirithunter'),
       (69, 'Trinity Spear'),
       (70, 'Daybreaker'),
       (71, 'Battleaxe'),
       (72, 'Greataxe'),
       (73, 'Hand of Khor'),
       (74, 'Halberd'),
       (75, 'Carrioncaller'),
       (76, 'Infernal Scythe'),
       (77, 'Bear Paws'),
       (78, 'Realmbreaker'),
       (79, 'Broadsword'),
       (80, 'Claymore'),
       (81, 'Dual Swords'),
       (82, 'Clarent Blade'),
       (83, 'Carving Sword'),
       (84, 'Galatine Pair'),
       (85, 'Kingmaker'),
       (86, 'Quarterstaff'),
       (87, 'Iron-clad Staff'),
       (88, 'Double Bladed Staff'),
       (89, 'Black Monk Stave'),
       (90, 'Soulscythe'),
       (91, 'Staff of Balance'),
       (92, 'Grailseeker'),
       (93, 'Hammer'),
       (94, 'Polehammer'),
       (95, 'Great Hammer'),
       (96, 'Tombhammer'),
       (97, 'Forge Hammers'),
       (98, 'Grovekeeper'),
       (99, 'Hand of Justice'),
       (100, 'Mace'),
       (101, 'Heavy Mace'),
       (102, 'Morning Star'),
       (103, 'Bedrock Mace'),
       (104, 'Incubus Mace'),
       (105, 'Camlann Mace'),
       (106, 'Oathkeepers'),
       (107, 'Brawler Gloves'),
       (108, 'Battle Bracers'),
       (109, 'Spiked Gauntlets'),
       (110, 'Ursine Maulers'),
       (111, 'Hellfire Hands'),
       (112, 'Ravenstrike Cestus'),
       (113, 'Fists of Avalon')
;

INSERT INTO off_hand(off_hand_id, off_hand_name)
VALUES (1, 'Shield'),
       (2, 'Sarcophagus'),
       (3, 'Caitiff Shield'),
       (4, 'Facebreaker'),
       (5, 'Astral Aegis'),
       (6, 'Tome of Spells'),
       (7, 'Diary'),
       (8, 'Eye of Secrets'),
       (9, 'Muisak'),
       (10, 'Taproot'),
       (11, 'Celestial Censer'),
       (12, 'Torch'),
       (13, 'Mistcaller'),
       (14, 'Sacred Scepter'),
       (15, 'Cryptcandle'),
       (16, 'Leering Cane')
;

INSERT INTO capes(cape_id, cape_name)
VALUES (1, 'Bridgewatch Cape'),
       (2, 'Fort Sterling Cape'),
       (3, 'Lymhurst Cape'),
       (4, 'Martlock Cape'),
       (5, 'Thetford Cape'),
       (6, 'Caerleon Cape'),
       (7, 'Heretic Cape'),
       (8, 'Undead Cape'),
       (9, 'Keeper Cape'),
       (10, 'Morgana Cape'),
       (11, 'Demon Cape')
;

INSERT INTO food(food_id, food_name)
VALUES (1, 'Pork Omelette'),
       (2, 'Dusthole Crab Omelette'),
       (3, 'Avalonian Pork Omelette'),
       (4, 'Beef Stew'),
       (5, 'Deadwater Eel Stew'),
       (6, 'Avalonian Beef Stew'),
       (7, 'Beef Sandwich'),
       (8, 'Avalonian Beef Sandwich')
;

INSERT INTO potions(potion_id, potion_name)
VALUES (1, 'Healing Potion'),
       (2, 'Energy Potion'),
       (3, 'Gigantify Potion'),
       (4, 'Resistance Potion'),
       (5, 'Sticky Potion'),
       (6, 'Poison Potion'),
       (7, 'Invisibility Potion')
;

INSERT INTO mounts(mount_id, mount_name)
VALUES (1, 'Swiftclaw'),
       (2, 'Armored Horse'),
       (3, 'Direwolf'),
       (4, 'Greywolf'),
       (5, 'Command Mammoth'),
       (6, 'Flame Basilisk'),
       (7, 'Venom Basilisk'),
       (8, 'Siege Ballista'),
       (9, 'Spectral Bat'),
       (10, 'Pest Lizard'),
       (11, 'Snow Husky'),
       (12, 'Black Panther'),
       (13, 'Morgana Raven'),
       (14, 'Gallant Horse'),
       (15, 'Battle Rhino'),
       (16, 'Tower Chariot'),
       (17, 'Battle Eagle'),
       (18, 'Colossus Beetle'),
       (19, 'Behemoth'),
       (20, 'Ancient Ent'),
       (21, 'Goliath Horseeater'),
       (22, 'Roving Bastion'),
       (23, 'Juggernaut'),
       (24, 'Phalanx Beetle')
;

INSERT INTO roles(id, name)
VALUES (1, 'ROLE_USER'),
       (2, 'ROLE_ADMIN')
;

INSERT INTO users (email, password, username)
VALUES ('cynical@tidal.com', 'test', 'CynicalEntity'),
       ('mg@gmail.com', 'test', 'matthew')
;

INSERT INTO regears (regear_id, character_name, chest_equivalent, chest_gear, chest_tier, event_id, guild_name,
                     head_equivalent, head_gear, head_tier, item_power, main_equivalent, main_hand, main_tier, shoes,
                     shoes_equivalent, shoes_tier, status, time_of_death)
VALUES (1, 'CynicalEntity', 8, 'Cleric Robe', '6.2', '492985911', 'Tidal', 8, 'Mercenary Hood', '6.2', 1507, 8,
        'Fallen Staff', '6.2', 'Scholar Sandals', 8, '7.1', 'pending', 'Fri, 17 Jun 2022 05:07 UTC')
;